const skills = [
  {
    name: "acrobatics",
    label: "Acrobatics",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "appraise",
    label: "Appraise",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "bluff",
    label: "Bluff",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "climb",
    label: "Climb",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "craft",
    label: "Craft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "diplomacy",
    label: "Diplomacy",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "disableDevice",
    label: "Disable Device",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "disguise",
    label: "Disguise",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "escapeArtist",
    label: "Escape Artist",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "fly",
    label: "Fly",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "handleAnimal",
    label: "Handle Animal",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
  {
    name: "heal",
    label: "Heal",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "intimidate",
    label: "Intimidate",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "knowledgeArcana",
    label: "Knowledge (Arcana)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeHistory",
    label: "Knowledge (History)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeLocal",
    label: "Knowledge (Local)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeNature",
    label: "Knowledge (Nature)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeNobility",
    label: "Knowledge (Nobility)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgePlanes",
    label: "Knowledge (Planes)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeReligion",
    label: "Knowledge (Religion)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeDungeoneering",
    label: "Knowledge (Dungeoneering)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeEngineering",
    label: "Knowledge (Engineering)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeGeography",
    label: "Knowledge (Geography)",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "linguistics",
    label: "Linguistics",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "perception",
    label: "Perception",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "perform",
    label: "Perform",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "profession",
    label: "Profession",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: true,
  },
  {
    name: "ride",
    label: "Ride",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "senseMotive",
    label: "Sense Motive",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "sleightOfHand",
    label: "Sleight of Hand",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "spellcraft",
    label: "Spellcraft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "stealth",
    label: "Stealth",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "survival",
    label: "Survival",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "swim",
    label: "Swim",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "useMagicDevice",
    label: "Use Magic Device",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
];
export default skills;
