const skills = [
  {
    name: "Acrobatics",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "Appraise",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "Bluff",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "Climb",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "Craft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "Diplomacy",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "Disable Device",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "Disguise",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "Escape Artist",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "Fly",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "Handle Animal",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
  {
    name: "Heal",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "Intimidate",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "Knowledge Arcana",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge History",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Local",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Nature",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Nobility",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Planes",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Religion",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Dungeoneering",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Engineering",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Knowledge Geography",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Linguistics",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Perception",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "Perform",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "Profession",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: true,
  },
  {
    name: "Ride",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "Sense Motive",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "Sleight of Hand",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "Spellcraft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "Stealth",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "Survival",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "Swim",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "Use Magic Device",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
];
export default skills;
