const skills = [
  {
    name: "acrobatics",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "appraise",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "bluff",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "climb",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "craft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: false,
  },
  {
    name: "diplomacy",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "disableDevice",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "disguise",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "escapeArtist",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "fly",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "handleAnimal",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
  {
    name: "heal",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "intimidate",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "knowledgeArcana",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeHistory",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeLocal",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeNature",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeNobility",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgePlanes",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeReligion",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeDungeoneering",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeEngineering",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "knowledgeGeography",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "linguistics",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "perception",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "perform",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: false,
  },
  {
    name: "profession",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: true,
  },
  {
    name: "ride",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "senseMotive",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "sleightOfHand",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: true,
  },
  {
    name: "spellcraft",
    ability: "Intelligence",
    modifier: "Int Modifier",
    trained: true,
  },
  {
    name: "stealth",
    ability: "Dexterity",
    modifier: "Dex Modifier",
    trained: false,
  },
  {
    name: "survival",
    ability: "Wisdom",
    modifier: "Wis Modifier",
    trained: false,
  },
  {
    name: "swim",
    ability: "Strength",
    modifier: "Str Modifier",
    trained: false,
  },
  {
    name: "useMagicDevice",
    ability: "Charisma",
    modifier: "Cha Modifier",
    trained: true,
  },
];
export default skills;
